// ── Stages ──
const STAGES = [
  { id: "order_placed", label: "Order Placed" },
  { id: "confirmed_preparing", label: "Confirmed / Preparing" },
  { id: "picked_up", label: "Picked up and on the way" },
  { id: "delivered", label: "Delivered" },
];

// ── Data (auto-generated by sync.js — DO NOT EDIT MANUALLY) ──
const DATA = {
  "order_placed": {
    "inapp": {
      "main": [
        {
          "scenario": "Confirming",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order has been placed",
            "ar": "تم تقديم الطلب",
            "ku": "داواکارییەکە جێگیر کرا"
          },
          "desc": {
            "en": "{VENDOR_NAME} is confirming your order",
            "ar": "{VENDOR_NAME} يقوم بتأكيد الطلب",
            "ku": "{VENDOR_NAME} داواکارییەکەت پشتڕاست دەکاتەوە"
          }
        },
        {
          "scenario": "Confirming — No Rider Yet",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order has been placed",
            "ar": "تم تقديم الطلب",
            "ku": "داواکارییەکە جێگیر کرا"
          },
          "desc": {
            "en": "We've got your order 🌟We'll take it from here and keep you updated",
            "ar": "استلمنا طلبك 🌟 سنهتم بالباقي ونخبرك بأي جديد",
            "ku": "داواکارییەکەتمان بەدەست گەیشت 🌟 ئەوەی تری لەسەر ئێمەیە و ئاگادارت دەکەینەوە"
          }
        },
        {
          "scenario": "Confirming — Rider Assigned",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "{RIDER_NAME} is your rider today",
            "ar": "{RIDER_NAME} سيقوم بتوصيل طلبك اليوم",
            "ku": "{RIDER_NAME} کارمەندی گەیاندنەکەتە بۆ ئەمڕۆ"
          },
          "desc": {
            "en": "We've sent your order to {VENDOR_NAME}",
            "ar": "قمنا بررسال طلبك إلى {VENDOR_NAME}",
            "ku": "ئێمە داواکارییەکەت ناردووە بۆ {VENDOR_NAME}"
          }
        },
        {
          "scenario": "Confirming Delayed",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order has been placed",
            "ar": "تم تقديم الطلب",
            "ku": "داواکارییەکە جێگیر کرا"
          },
          "desc": {
            "en": "There is a high demand right now, but we're on it. We'll update you once preparation starts",
            "ar": "يوجد عدد كبير من الطلبات حاليًا، لكننا نتابع طلبك وسنخبرك عندما يبدأ بتحضير الطلب.",
            "ku": "لە ئێستادا داخوازییەکی زۆر هەیە، بەڵام کاری لەسەر دەکەین. هەرکات ئامادەکارییەکان دەستیان پێ کرد ئاگادارت دەکەینەوە"
          }
        },
        {
          "scenario": "Generic Status",
          "surfaces": [
            "otp"
          ],
          "en": "Your order has been sent! We'll take care of the rest and keep you updated 🌟",
          "ar": "تم إرسال طلبك! سنعتني بالباقي ونخبرك بكل جديد 🌟",
          "ku": "داواکارییەکەت نێردراوە! ئەوەی تری لەسەر ئێمەیە و لە گۆڕانکارییەکان ئاگادارت دەکەینەوە! 🌟"
        },
        {
          "scenario": "Rider Assigned Status",
          "surfaces": [
            "otp"
          ],
          "en": "{RIDER_NAME} is your rider today. They’re heading to {VENDOR_NAME} now 🛵",
          "ar": "{RIDER_NAME} في طريقه إلى {VENDOR_NAME} ليستلم طلبك ويقوم بتوصيله إليك 🛵",
          "ku": "{RIDER_NAME} کارمەندی گەیاندنتە بۆ ئەمڕۆ. ئێستا بە ڕێگاوەیە بۆ {VENDOR_NAME} 🛵"
        },
        {
          "scenario": "Saturated Fleet",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "It’s a busy time for orders, so it’s taking a bit longer to find a rider. Hang tight, we’re on it 🙌",
          "ar": "نظراً لكثرة الطلبات حالياً، يستغرق الأمر وقتًا أطول لإيجاد سائق. انتظر قليلاً، نحن نعمل على ذلك 🙌",
          "ku": "لە ئێستادا داواکارییەکی زۆر هەیە، بۆیە کاتێکی زیاتری دەوێت تا کارمەندێکی گەیاندن دەدۆزینەوە. کەمێک چاوەڕێ بکە، ئێمە کاری لەسەر دەکەین 🙌"
        },
        {
          "scenario": "Change in Staffing",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "It’s taking a bit longer to find a rider, but {VENDOR_NAME} is preparing your order now. We’ll keep you updated",
          "ar": "نظراً لكثرة الطلبات حالياً، يستغرق الأمر وقتًا أطول لإيجاد سائق، لكن {VENDOR_NAME} يُجهز طلبك الآن",
          "ku": "کەمێک زیاتری پێ دەچێت تا کارمەندێکی گەیاندن دەدۆزینەوە، بەڵام {VENDOR_NAME} ئێستا داواکارییەکەت ئامادە دەکات. لە گۆڕانکارییەکان ئاگادارت دەکەیەنەوە"
        }
      ],
      "timeline": [
        {
          "scenario": "Header",
          "surfaces": [
            "otp"
          ],
          "en": "Here's how your order is going",
          "ar": "إليك آخر تحديثات طلبك",
          "ku": "بارودۆخی داواکارییەکەت بەم شێوەیەیە"
        },
        {
          "scenario": "Order Placed (Complete)",
          "surfaces": [
            "otp"
          ],
          "en": "Order placed",
          "ar": "استلمنا الطلب",
          "ku": "داواکاری تۆمار کرا"
        },
        {
          "scenario": "Vendor Confirming (Active) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "{VENDOR_NAME} confirming your order",
          "ar": "{VENDOR_NAME} يقوم بتأكيد طلبك",
          "ku": "{VENDOR_NAME} داواکارییەکەت پەسەند دەکات"
        },
        {
          "scenario": "Vendor Confirming (Active) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "It’s a little busy at {VENDOR_NAME}, but things should start moving shortly 🙌",
          "ar": "الوضع مزدحم قليلًا في {VENDOR_NAME}، لكننا نتابع طلبك 🙌",
          "ku": "لای {VENDOR_NAME} کەمێک جەنجاڵە، بەڵام بەم زوانە کارەکان دەست پێدەکەنەوە 🙌"
        },
        {
          "scenario": "Vendor Confirming (Complete) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "{VENDOR_NAME} confirmed your order",
          "ar": "{VENDOR_NAME} قام بتأكيد طلبك",
          "ku": "{VENDOR_NAME} داواکارییەکەتی پەسەند کرد"
        },
        {
          "scenario": "Vendor Confirming (Complete) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "It was a bit busy at {VENDOR_NAME}, so your order took a little longer to confirm",
          "ar": "كان الوضع مزدحمًا قليلًا في {VENDOR_NAME}، لذا استغرق تأكيد طلبك وقتًا أطول",
          "ku": "لای {VENDOR_NAME} کەمێک جەنجاڵ بوو، بۆیە پەسەندکردنی داواکارییەکەت کەمێک زیاتری خایاند"
        },
        {
          "scenario": "Vendor Confirming (Inactive)",
          "surfaces": [
            "otp"
          ],
          "en": "{VENDOR_NAME} confirming your order",
          "ar": "{VENDOR_NAME} يقوم بتأكيد طلبك",
          "ku": "{VENDOR_NAME} داواکارییەکەت پەسەند دەکات"
        },
        {
          "scenario": "Footer",
          "surfaces": [
            "otp"
          ],
          "en": "Continue to Help Center",
          "ar": "المتابعة إلى مركز المساعدة",
          "ku": "بەردەوام بە بۆ سەنتەری هاوکاری"
        }
      ],
      "indicators": [
        {
          "scenario": "Badge — Order Placed",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "Order placed",
          "ar": "استلمنا الطلب",
          "ku": "داواکاری جێگیر کرا"
        },
        {
          "scenario": "On Time Tag",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "On time",
          "ar": "في الموعد",
          "ku": "لە کاتی خۆیدا"
        },
        {
          "scenario": "Updated Time Tag",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "Updated time",
          "ar": "تغيّر الوقت",
          "ku": "کاتی نوێکراوە"
        },
        {
          "scenario": "Delay Tag Tooltip",
          "surfaces": [
            "otp"
          ],
          "en": "Tap here to see more details on your order",
          "ar": "اضغط هنا للمزيد من التفاصيل عن طلبك",
          "ku": "پەنجە لێرە بدە بۆ بینینی وردەکاریی زیاتری داواکارییەکەت"
        }
      ]
    },
    "push": [
      {
        "scenario": "Order Accepted — Title",
        "en": "Your order is confirmed",
        "ar": "تم تأكيد طلبك",
        "ku": "داواکارییەکەت پشتڕاست کرایەوە"
      },
      {
        "scenario": "Order Accepted — Message",
        "en": "{RESTAURANT_NAME} is on it! Great stuff is coming your way",
        "ar": "{RESTAURANT_NAME} بدأ بتجهيز طلبك! أشياء رائعة في طريقها إليك",
        "ku": "{RESTAURANT_NAME} دەستی بە ئامادەکردن کرد! شتی خۆش بەڕێوەیە"
      }
    ],
    "sms": [
      {
        "scenario": "Order Sent to Restaurant",
        "en": "Thanks for ordering from Talabat.com. Your Order is sent to Restaurant. You will receive a call shortly to verify your information.",
        "ar": "شكرا لاختيارك طلبات. لقد قمنا باستلام طلبك. سنقوم بالاتصال بك لتأكيد بياناتك."
      },
      {
        "scenario": "Accepted by Vendor",
        "en": "Your order has been accepted by {REST_NAME} and will reach you soon!",
        "ar": "لقد تم قبول طلبك من {REST_NAME} توقع وصوله قريباً."
      },
      {
        "scenario": "Accepted by Vendor (with ETA)",
        "en": "Your order has been accepted by {REST_NAME} and should reach you by {EDT}.",
        "ar": "لقد تم قبول طلبك من {REST_NAME} والوقت المتوقع للوصول هو {EDT}"
      }
    ],
    "email": []
  },
  "confirmed_preparing": {
    "inapp": {
      "main": [
        {
          "scenario": "Preparing",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "{VENDOR_NAME} is on it! Getting things ready",
            "ar": "{VENDOR_NAME} يعمل على تجهيز طلبك!",
            "ku": "{VENDOR_NAME} داواکارییەکەت ئامادە دەکا!"
          }
        },
        {
          "scenario": "Preparing — Getting Ready v2",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "{VENDOR_NAME} is on it! They're getting things ready",
            "ar": "{VENDOR_NAME} يعمل على تجهيز طلبك!",
            "ku": "{VENDOR_NAME} داواکارییەکەت ئامادە دەکا!"
          }
        },
        {
          "scenario": "Preparing — Rider on Way",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "{RIDER_NAME} is on their way to pick it up",
            "ar": "{RIDER_NAME} في طريقه لاستلام طلبك",
            "ku": "{RIDER_NAME} لە ڕێگەیە بۆ وەرگرتنی داواکارییەکەت"
          }
        },
        {
          "scenario": "Preparing — Rider at Vendor",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "{RIDER_NAME} is at {VENDOR_NAME} to pick it up",
            "ar": "{RIDER_NAME} وصل إلى {VENDOR_NAME} لإستلام الطلب",
            "ku": "{RIDER_NAME} گەیشتووە بۆ {VENDOR_NAME} تا وەریبگرێ"
          }
        },
        {
          "scenario": "Preparing — Rider Near Pickup",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "{RIDER_NAME} is at {VENDOR_NAME}",
            "ar": "{RIDER_NAME} وصل إلى {VENDOR_NAME}",
            "ku": "{RIDER_NAME} گەیشتە {VENDOR_NAME}"
          },
          "desc": {
            "en": "They will pick up your order once it's ready",
            "ar": "سيستلم الطلب بمجرد أن يصبح جاهزًا",
            "ku": "هەر کات داواکارییەکەت ئامادە بوو وەریدەگرن"
          }
        },
        {
          "scenario": "Preparing — Good Things",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Good things in progress...",
            "ar": "أشياء رائعة قيد التحضير...",
            "ku": "شتێ باش لە ئامادەکاریدایە..."
          },
          "desc": {
            "en": "{VENDOR_NAME} is on it! Great stuff is coming your way",
            "ar": "{VENDOR_NAME} يعمل على طلبك! اشياء رائعة في طريقها إليك",
            "ku": "{VENDOR_NAME} کاری لەسەر دەکات! شتی نایاب لە ڕێگەیە بەرەو لای تۆ"
          }
        },
        {
          "scenario": "Preparing — Speeding Up",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Speeding things up...",
            "ar": "نعمل على تسريع الأمور...",
            "ku": "کار دەکەین بۆ خێراکردنی شتەکان..."
          },
          "desc": {
            "en": "{VENDOR_NAME} is on it! They're getting things ready",
            "ar": "{VENDOR_NAME} يعمل على تجهيز طلبك!",
            "ku": "{VENDOR_NAME} داواکارییەکەت ئامادە دەکا!"
          }
        },
        {
          "scenario": "Preparing — Vendor Busy",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "Everything's on track - it's just a little busy at {VENDOR_NAME}, but they are on it",
            "ar": "طلبك في الموعد، يوجد ازدحام بسيط لدى {VENDOR_NAME} لكنهم يعملون على تحضير طلبك",
            "ku": "هەموو شتێک لەسەر ڕێچکەی خۆیەتی - کەمێک سەرقاڵن لە {VENDOR_NAME}، بەڵام کاری لەسەر دەکەن"
          }
        },
        {
          "scenario": "Preparing Delayed — No Rider",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "We'll let you know as soon as your order is ready and picked up 🛵",
            "ar": "سنخبرك بمجرد أن يجهز طلبك ويستلمه السائق 🛵",
            "ku": "ئێمە ئاگادارت دەکەینەوە هەرکات داواکارییەکەت ئامادەبوو و هەڵگیرا 🛵"
          }
        },
        {
          "scenario": "Preparing Delayed — Rider Assigned",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "It's a little busy, but no worries, your order will be ready and picked up shortly",
            "ar": "يوجد ازدحام بسيط لكن لا تقلق، سيتم تجهيز طلبك واستلامه قريبًا",
            "ku": "کەمێک سەرقاڵن، بەڵام خەمت نەبێ، داواکارییەکەت کەمێکی تر ئامادە دەبێ و هەڵدەگیرێ"
          }
        },
        {
          "scenario": "Preparing Delayed — Generic",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "You should get your delivery by {PROMISED_TIME}. It's a bit busier than usual, but we're on it🙏",
            "ar": "من المتوقع وصول طلبك في الساعة {PROMISED_TIME}. الازدحام أكثر من المعتاد، لكننا نتابع الموضوع 🙏",
            "ku": "پێشبینی دەکرێ داواکارییەت لە {PROMISED_TIME} بگات. کەمێک قەرەباڵغترە وەک لە کاتی ئاسایی، بەڵام کاری لەسەر دەکەین 🙏"
          }
        },
        {
          "scenario": "Preparing Delayed — Vendor",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Preparing your order",
            "ar": "يتم تحضير طلبك",
            "ku": "داواکارییەکەت ئامادە دەکرێت"
          },
          "desc": {
            "en": "We've checked in with {VENDOR_NAME} to finish up your order shortly - hang tight",
            "ar": "تواصلنا مع {VENDOR_NAME} لتسريع طلبك، انتظر قليلًا",
            "ku": "پەیوەندیمان بە {VENDOR_NAME} کرد بۆ تەواوکردنی داواکارییەت بە زووترین کات - کەمێک چاوەڕێ بە"
          }
        },
        {
          "scenario": "Preparing — Generic Status",
          "surfaces": [
            "otp"
          ],
          "en": "{VENDOR_NAME} is on it! Great stuff is coming your way",
          "ar": "{VENDOR_NAME} يعمل على طلبك! اشياء رائعة في طريقها إليك",
          "ku": "{VENDOR_NAME} کاری لەسەر دەکات! شتی نایاب لە ڕێگەیە بەرەو لای تۆ"
        },
        {
          "scenario": "Rider Assigned Status",
          "surfaces": [
            "otp"
          ],
          "en": "{RIDER_NAME} is on their way to pick up your order from {VENDOR_NAME} 🛵",
          "ar": "{RIDER_NAME} في طريقه لاستلام طلبك من {VENDOR_NAME}🛵",
          "ku": "{RIDER_NAME} لە ڕێگەیە بۆ هەڵگرتنی داواکارییەکەت لە {VENDOR_NAME} 🛵"
        },
        {
          "scenario": "Rider Near Pickup Status",
          "surfaces": [
            "otp"
          ],
          "en": "{RIDER_NAME} has arrived at {VENDOR_NAME} on time. If you have any questions, you can reach out to your rider 🛵",
          "ar": "{RIDER_NAME} قد وصل إلى {VENDOR_NAME} في الوقت المحدد. إذا كانت لديك اسئلة، يمكنك التواصل معه 🛵",
          "ku": "{RIDER_NAME} لە کاتی خۆیدا گەیشتووە بۆ {VENDOR_NAME}. ئەگەر هەر پرسیارێکت هەیە دەتوانیت پەیوەندی بە کارمەندی گەیاندنەکەتەوە بکەیت 🛵"
        },
        {
          "scenario": "Rider Arrived at Vendor Status",
          "surfaces": [
            "otp"
          ],
          "en": "{RIDER_NAME} is at {VENDOR_NAME} and ready to grab your order 🛵",
          "ar": "{RIDER_NAME} وصل إلى {VENDOR_NAME} وهو جاهز لاستلام طلبك 🛵",
          "ku": "{RIDER_NAME} لە کاتی خۆیدا لە {VENDOR_NAME} ئامادەیە و داواکارییەکەت هەڵدەگرێت 🛵"
        },
        {
          "scenario": "Vendor Late Status",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Things are busy at {VENDOR_NAME}, so it’s taking a bit longer to prepare your order. We’ll keep you updated 🙌",
          "ar": "{VENDOR_NAME} مشغول حالياً، لذلك سيستغرق إعداد طلبك وقتًا أكثر. سنبقيك على اطلاع بكل جديد 🙌",
          "ku": "{VENDOR_NAME} کەمێک سەرقاڵە، بۆیە ئامادەکردنی داواکارییەکەت کەمێک زیاتری پێ دەچێت. ئێمە لە گۆڕانکارییەکان ئاگادارت دەکەینەوە 🙌"
        }
      ],
      "timeline": [
        {
          "scenario": "Rider Assigned (Active) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Finding a rider",
          "ar": "جاري العثور على سائق",
          "ku": "گەڕان بۆ کارمەندی گەیاندندا"
        },
        {
          "scenario": "Rider Assigned (Active) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "It’s busier than usual, but we’re finding you the nearest rider shortly 🛵",
          "ar": "الوضع أكثر ازدحامًا من المعتاد، لكننا سنجد لك سائق قريبًا 🛵",
          "ku": "لە ئاسایی جەنجاڵترە، بەڵام بەم زوانە نزیکترین کارمەندی گەیاندنت بۆ دەدۆزینەوە🛵"
        },
        {
          "scenario": "Rider Assigned (Complete) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Rider assigned",
          "ar": "تم تعيين سائق",
          "ku": "کارمەندی گەیاندن دیاری کرا"
        },
        {
          "scenario": "Rider Assigned (Complete) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "It took a bit longer to find a rider due to high demand",
          "ar": "استغرق العثور على سائق وقتًا أطول بسبب ارتفاع عدد الطلبات",
          "ku": "بە هۆی زۆریی داواکارییەکانەوە، دۆزینەوەی کارمەندی گەیاندن کەمێک زیاتری خایاند"
        },
        {
          "scenario": "Rider Assigned (Inactive)",
          "surfaces": [
            "otp"
          ],
          "en": "Finding a rider",
          "ar": "جاري العثور على سائق",
          "ku": "گەڕان بۆ کارمەندی گەیاندندا"
        },
        {
          "scenario": "Rider at Vendor (Active) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Rider on the way to {VENDOR_NAME}",
          "ar": "السائق في طريقه إلى {VENDOR_NAME}",
          "ku": "کارمەندی گەیاندن لە ڕێگایە بەرەو {VENDOR_NAME}"
        },
        {
          "scenario": "Rider at Vendor (Active) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "Just a few mins late, but your rider will arrive at {VENDOR_NAME} shortly 🛵",
          "ar": "تأخر السائق بضع دقائق فقط، وسيصل إلى {VENDOR_NAME} قريبًا 🛵",
          "ku": "تەنها چەند خولەکێک دواکەوتووە، بەم زوانە کارمەندی گەیاندن دەگاتە لای {VENDOR_NAME} 🛵"
        },
        {
          "scenario": "Rider at Vendor (Complete) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Rider arrived at {VENDOR_NAME}",
          "ar": "وصل السائق إلى {VENDOR_NAME}",
          "ku": "کارمەندی گەیاندن گەیشتە لای {VENDOR_NAME}"
        },
        {
          "scenario": "Rider at Vendor (Complete) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "It took a little longer on the way to {VENDOR_NAME}",
          "ar": "استغرق الوصول إلى {VENDOR_NAME} وقتًا أطول قليلًا",
          "ku": "لە ڕێگەی بەرەو {VENDOR_NAME} کەمێک زیاتری خایاند"
        },
        {
          "scenario": "Rider at Vendor (Inactive)",
          "surfaces": [
            "otp"
          ],
          "en": "Rider on the way to {VENDOR_NAME}",
          "ar": "السائق في طريقه إلى {VENDOR_NAME}",
          "ku": "کارمەندی گەیاندن لە ڕێگایە بەرەو {VENDOR_NAME}"
        },
        {
          "scenario": "Preparing for Pickup (Active) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Preparing your order",
          "ar": "جاري تجهيز طلبك",
          "ku": "داواکارییەکەت ئامادە دەکرێت"
        },
        {
          "scenario": "Preparing for Pickup (Active) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "Things seem a bit busy, but we’ve notified {VENDOR_NAME} to speed up your order 🙌",
          "ar": "يبدو أن الأمور مزدحمة قليلًا، لكننا أبلغنا {VENDOR_NAME} لتسريع تجهيز طلبك 🙌",
          "ku": "وا دیارە کەمێک جەنجاڵ بێت، بەڵام {VENDOR_NAME}ـمان ئاگادار کردووەتەوە بۆ خێراکردنی داواکارییەکەت 🙌"
        },
        {
          "scenario": "Preparing for Pickup — Rider Delayed (Active) — Title",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Order ready for pickup",
          "ar": "الطلب جاهز للاستلام",
          "ku": "داواکاری ئامادەیە بۆ هەڵگرتن"
        },
        {
          "scenario": "Preparing for Pickup — Rider Delayed (Active) — Subtitle",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Your rider is picking up your order and should be on the way to you shortly",
          "ar": "السائق يستلم طلبك الآن وسيكون في طريقه إليك قريبًا",
          "ku": "کارمەندی گەیاندنەکەت داواکارییەکەت هەڵدەگرێت و کەمێکی تر بەرەو لای تۆ بەڕێ دەکەوێ"
        },
        {
          "scenario": "Preparing for Pickup (Complete) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Order ready and picked up",
          "ar": "تم تجهيز الطلب واستلامه",
          "ku": "داواکارییەکە ئامادەیە وهەڵگیرا"
        },
        {
          "scenario": "Preparing for Pickup (Complete) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "It was a bit busy at {VENDOR_NAME}, so your order took a little longer to prepare",
          "ar": "كان الوضع مزدحمًا قليلًا في {VENDOR_NAME}، لذا استغرق تجهيز طلبك وقتًا أطول",
          "ku": "لای {VENDOR_NAME} کەمێک جەنجاڵ بوو، بۆیە ئامادەکردنی داواکارییەکەت کەمێک زیاتری خایاند"
        },
        {
          "scenario": "Preparing for Pickup — Rider Delayed (Complete) — Subtitle",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "It took a little more time to pick up your order",
          "ar": "استغرق استلام طلبك وقتًا أطول قليلًا من المعتاد",
          "ku": "کەمێک کاتی زیاتری پێ چوو بۆ هەڵگرتنی داواکارییەکەت"
        },
        {
          "scenario": "Preparing for Pickup (Inactive)",
          "surfaces": [
            "otp"
          ],
          "en": "Preparing your order",
          "ar": "جاري تجهيز طلبك",
          "ku": "داواکارییەکەت ئامادە دەکرێت"
        }
      ],
      "indicators": [
        {
          "scenario": "Badge — Preparing",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "Preparing order",
          "ar": "قيد التحضير",
          "ku": "ئامادەکردنی داواکاری"
        },
        {
          "scenario": "Badge — On Time",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "On time",
          "ar": "في الموعد",
          "ku": "لە کاتی خۆیدا"
        },
        {
          "scenario": "Badge — Time Changed",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "Time Changed",
          "ar": "تغير الوقت"
        }
      ]
    },
    "push": [
      {
        "scenario": "Order Near Vendor — Title",
        "en": "Your rider's arriving at {RESTAURANT_NAME}",
        "ar": "السائق وصل إلى {RESTAURANT_NAME}",
        "ku": "کارمەندی گەیاندنەکەت گەیشتە  {RESTAURANT_NAME}"
      },
      {
        "scenario": "Order Near Vendor — Message",
        "en": "They will pick up your order as soon as it's ready",
        "ar": "سيستلم الطلب بمجرد أن يصبح جاهزًا",
        "ku": "هەر کات داواکارییەکەت ئامادە بوو، وەریدەگرن"
      }
    ],
    "sms": [
      {
        "scenario": "Delivery Delay (Agent-sent)",
        "en": "Hi from [Brand]. We've contacted the restaurant and it seems there's going to be a slight delay in your delivery time. Please bear with us.",
        "ar": "مرحبًا، قمنا بالتواصل مع المطعم بخصوص طلبك وقد يكون هناك بعض التأخير في توصيل الطلب. نرجو الانتظار قليلاً وشكرًا لتفهمك.",
        "delay": true
      },
      {
        "scenario": "Prayer Time Delay",
        "en": "Thanks for ordering from Talabat.com. Your order is sent to Restaurant & might be delayed due to prayer time.",
        "ar": "شكرا لاختيارك طلبات. من الممكن أن يكون هناك تأخير طفيف في التوصيل بسبب وقت الصلاة.",
        "delay": true
      },
      {
        "scenario": "Cancelled — Prep Delays",
        "en": "Hi from Talabat. Unfortunately your order [Order ID] was cancelled because of preparation delays.",
        "ar": "نعتذر. تم إلغاء الطلب [Order ID] بسبب تاخر التوصيل."
      },
      {
        "scenario": "Cancelled — Restaurant Busy",
        "en": "Hi from Talabat. Unfortunately [Resto Name] has cancelled your order due to a rush in orders.",
        "ar": "مرحبا. للأسف تم إلغاء طلبك من قبل [Resto Name] بسبب ازدياد مفاجئ لعدد الطلبات."
      },
      {
        "scenario": "Cancelled — No Riders",
        "en": "Hi from Talabat. Unfortunately your order [Order ID] was cancelled because the restaurant had no available riders.",
        "ar": "نعتذر. تم إلغاء الطلب [Order ID] بسبب عدم توفر سائقين التوصيل لدى المطعم. بإمكانك وضع طلب آخر."
      },
      {
        "scenario": "Cancelled — Not Responding",
        "en": "Hi from Talabat. Unfortunately we had to cancel your order [Order ID] because the restaurant is not responding.",
        "ar": "نعتذر. تم إلغاء الطلب [Order ID] بسبب عدم توفر المطعم. بإمكانك وضع طلب آخر."
      },
      {
        "scenario": "Cancelled — Item Unavailable",
        "en": "Hi from Talabat. Your order [Order ID] is cancelled due to item unavailability.",
        "ar": "مرحبا. تم إلغاء طلبك [Order ID] بسبب عدم توفر عنصر من الطلب."
      }
    ],
    "email": []
  },
  "picked_up": {
    "inapp": {
      "main": [
        {
          "scenario": "Delivering",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order is on the way",
            "ar": "طلبك في الطريق إليك",
            "ku": "داواکاری لە ڕێگەیە"
          },
          "desc": {
            "en": "{RIDER_NAME} is on their way to you now",
            "ar": "{RIDER_NAME} في طريقه إليك الآن",
            "ku": "{RIDER_NAME} ئێستا لە ڕێگەیە"
          }
        },
        {
          "scenario": "Delivering — Heading Your Way",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Heading your way...",
            "ar": "في الطرق إليك...",
            "ku": "لە ڕێگەیە بەرەو لای تۆ..."
          },
          "desc": {
            "en": "{RIDER_NAME} is on their way to you now",
            "ar": "{RIDER_NAME} في طريقه إليك الآن",
            "ku": "{RIDER_NAME} ئێستا لە ڕێگەیە"
          }
        },
        {
          "scenario": "Delivering — Order Nearby",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order is nearby",
            "ar": "طلبك على وشك الوصول",
            "ku": "داواکارییەکەت نزیکە"
          },
          "desc": {
            "en": "Get ready! {RIDER_NAME} is about to drop off your order",
            "ar": "استعد! {RIDER_NAME} على وشك الوصول إليك",
            "ku": "ئامادەبە! {RIDER_NAME} خەریکە داواکارییەکەت دەگەیەنێت"
          }
        },
        {
          "scenario": "Delivering — Rider Nearby",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "{RIDER_NAME} is nearby",
            "ar": "{RIDER_NAME} قريب منك",
            "ku": "{RIDER_NAME} نزیکە"
          },
          "desc": {
            "en": "Get ready! {RIDER_NAME} is about to drop off your order",
            "ar": "استعد! {RIDER_NAME} على وشك الوصول إليك",
            "ku": "ئامادەبە! {RIDER_NAME} خەریکە داواکارییەکەت دەگەیەنێت"
          }
        },
        {
          "scenario": "Near Drop-off — Delayed",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order is nearby",
            "ar": "طلبك على وشك الوصول",
            "ku": "داواکارییەکەت نزیکە"
          },
          "desc": {
            "en": "A quick call might help them to find you faster",
            "ar": "مكالمة سريعة قد تساعده في الوصول إليك أسرع",
            "ku": "یەک تەلەفۆنی خێرا ڕەنگە یارمەتیی بدا زووتر بتدۆزێتەوە"
          }
        },
        {
          "scenario": "Moderate Delay — On Way",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order is on the way",
            "ar": "طلبك في الطريق إليك",
            "ku": "داواکاری لە ڕێگەیە"
          },
          "desc": {
            "en": "Just a few mins late, but {RIDER_NAME} is on the way to you now 🛵",
            "ar": "تأخر {RIDER_NAME} قليلاً، لكنه في طريقه إليك الآن 🛵",
            "ku": "{RIDER_NAME} چەند خولەکێک دواکەوتووە، بەڵام ئێستا لە ڕێگەن بەرەو لای تۆ 🛵"
          }
        },
        {
          "scenario": "Severe Delay — On Way",
          "delay": true,
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order is on the way",
            "ar": "طلبك في الطريق إليك",
            "ku": "داواکاری لە ڕێگەیە"
          },
          "desc": {
            "en": "Things were taking a bit longer, but {RIDER_NAME} should reach shortly",
            "ar": "حصل تأخير بسيط، لكن {RIDER_NAME} في الطريق إليك وسيصل خلال لحظات",
            "ku": "شتەکان تۆزێک زیاتریان خایاند، بەڵام {RIDER_NAME} کەمێکی تر دەگاتە لات"
          }
        },
        {
          "scenario": "Other Nearby Delivery",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order is on the way",
            "ar": "طلبك في الطريق إليك",
            "ku": "داواکاری لە ڕێگەیە"
          },
          "desc": {
            "en": "{RIDER_NAME} is completing another delivery nearby and will be heading to you on time 🛵",
            "ar": "{RIDER_NAME} يقوم بتوصيل طلب آخر بالقرب منك وسيكون عندك في الوقت المحدد 🛵",
            "ku": "{RIDER_NAME} داواکارییەکی تر دەگەیەنێت لەم نزیکانە و لە کاتی خۆیدا دەگاتە لای تۆ 🛵"
          }
        },
        {
          "scenario": "PIN Code",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Your order is on the way",
            "ar": "طلبك في الطريق إليك",
            "ku": "داواکاری لە ڕێگەیە"
          },
          "desc": {
            "en": "Your order code is {PIN_CODE}. Please share it with your rider at delivery",
            "ar": "رمز طلبك هو {PIN_CODE}. شاركه مع السائق وقت تسليم الطلب",
            "ku": "کۆدەکەت بریتییە لە {PIN_CODE}. تکایە لەگەڵ کارمەندی گەیاندنەکەت هاوبەشی بکە لە کاتی گەیاندندا"
          }
        },
        {
          "scenario": "Delivering — Generic Status",
          "surfaces": [
            "otp"
          ],
          "en": "Your order is on the move! We’ll let you know when {RIDER_NAME} is nearby",
          "ar": "طلبك في الطريق! سنعلمك عندما يكون {RIDER_NAME} قريبًا",
          "ku": "داواکارییەکەت لە ڕێگەیە! ئاگادارت دەکەینەوە کاتێک {RIDER_NAME} نزیک کەوتەوە"
        },
        {
          "scenario": "Near Drop-off Status",
          "surfaces": [
            "otp"
          ],
          "en": "Almost there! Give {RIDER_NAME} a moment to drop off your order",
          "ar": "{RIDER_NAME} على وشك الوصول! لحظات وسيكون طلبك بين يديك",
          "ku": "زۆری نەماوە! کەمێک کات بدە بە {RIDER_NAME} تا داواکارییەکەت دەگەیەنێت"
        },
        {
          "scenario": "Rider Reached Drop-off",
          "surfaces": [
            "otp"
          ],
          "en": "Almost there! Give {RIDER_NAME} a moment to drop off your order",
          "ar": "{RIDER_NAME} على وشك الوصول! لحظات وسيكون طلبك بين يديك",
          "ku": "زۆری نەماوە! کەمێک کات بدە بە {RIDER_NAME} تا داواکارییەکەت دەگەیەنێت"
        },
        {
          "scenario": "Overall Order Late",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Your order is delayed, but {RIDER_NAME} has picked it up and is on their way to you now",
          "ar": "تأخر طلبك قليلاً، لكن {RIDER_NAME} استلمه الآن وهو في طريقه إليك",
          "ku": "داواکارییەکەت دوا کەوتووە، بەڵام {RIDER_NAME} داواکارییەکەی هەڵگرتووە و لە ڕێگەدایە بەرەو تۆ"
        }
      ],
      "timeline": [
        {
          "scenario": "Rider on the Way (Active) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Order on the way",
          "ar": "الطلب في الطريق",
          "ku": "داواکارییەکە لە ڕێگەیە"
        },
        {
          "scenario": "Rider on the Way (Active) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "Your rider is arriving shortly to pick up your order",
          "ar": "سيصل السائق قريبًا لاستلام طلبك",
          "ku": "کارمەندی گەیاندنەکەت کەمێکی تر دەگات بۆ هەڵگرتنی داواکارییەکەت"
        },
        {
          "scenario": "Rider on the Way (Complete) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Rider arrived nearby",
          "ar": "السائق وصل قريب من موقعك",
          "ku": "کارمەندی گەیاندن لە نزیک شوێنەکەتە"
        },
        {
          "scenario": "Rider on the Way (Complete) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "Traffic slowed things down a bit along the way",
          "ar": "تسبب ازدحام المرور في بعض التأخير على الطريق",
          "ku": "ترافیک و جەنجاڵی کارەکانی کەمێک خاو کردەوە"
        },
        {
          "scenario": "Rider on the Way (Inactive)",
          "surfaces": [
            "otp"
          ],
          "en": "Order on the way",
          "ar": "الطلب في الطريق",
          "ku": "داواکارییەکە لە ڕێگەیە"
        },
        {
          "scenario": "Delivering Order (Active) — Title",
          "surfaces": [
            "otp"
          ],
          "en": "Rider dropping off your order",
          "ar": "السائق يسلّم طلبك",
          "ku": "کارمەندی گەیاندن داواکارییەکەت ڕادەست دەکات"
        },
        {
          "scenario": "Delivering Order (Active) — Subtitle",
          "surfaces": [
            "otp"
          ],
          "en": "A quick call might help them find you faster 🙏",
          "ar": "مكالمة سريعة قد تساعدهم في الوصول إليك بشكل أسرع 🙏",
          "ku": "پەیوەندییەکی کورت یارمەتیی دەدات خێراتر بتدۆزێتەوە 🙏"
        },
        {
          "scenario": "Delivering Order (Complete)",
          "surfaces": [
            "otp"
          ],
          "en": "Order delivered",
          "ar": "تم توصيل الطلب",
          "ku": "داواکارییەکە گەیشت"
        },
        {
          "scenario": "Delivering Order (Inactive)",
          "surfaces": [
            "otp"
          ],
          "en": "Rider dropping off your order",
          "ar": "السائق يسلّم طلبك",
          "ku": "کارمەندی گەیاندن داواکارییەکەت ڕادەست دەکات"
        }
      ],
      "tgo": [
        {
          "scenario": "Arrives At Label",
          "surfaces": [
            "otp"
          ],
          "en": "Arrives at",
          "ar": "يصل خلال",
          "ku": "دەگات لە"
        },
        {
          "scenario": "Estimated Arrival",
          "surfaces": [
            "otp"
          ],
          "en": "Estimated arrival",
          "ar": "وقت  الوصول المتوقع",
          "ku": "کاتی گەیشتنی خەمڵێنراو"
        }
      ],
      "indicators": [
        {
          "scenario": "Badge — Delivering",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "On the way",
          "ar": "قيد التوصيل",
          "ku": "لە ڕێگەیە"
        }
      ]
    },
    "push": [
      {
        "scenario": "Order Picked Up — Title",
        "en": "Your order’s on the way 🛵",
        "ar": "السائق في طريقه إليك 🛵",
        "ku": "کارمەندی گەیاندنەکەت لە ڕێگەیە 🛵"
      },
      {
        "scenario": "Order Picked Up — Message",
        "en": "We’ll let you know when your rider's nearby",
        "ar": "سننبهك عندما يقترب من الموقع",
        "ku": "ئاگادارت دەکەینەوە هەرکات نزیک بۆوە"
      },
      {
        "scenario": "Order Near Customer — Title",
        "en": "Your rider's nearby 🎉",
        "ar": "طلبك على وشك الوصول 🎉",
        "ku": "کارمەندی گەیاندنەکەت نزیکە 🎉"
      },
      {
        "scenario": "Order Near Customer — Message",
        "en": "Just around the corner! Give them a moment to drop off your order",
        "ar": "دقائق وسيكون الطلب بين يديك!",
        "ku": "زۆر نزیکە! کەمێکی تر داواکارییەکە دەگاتە دەستت"
      },
      {
        "scenario": "Rider Nearby",
        "en": "Your rider’s just around the corner! Give them a moment to drop off your order",
        "ar": "السائق على وشك الوصول! دقائق وسيكون الطلب بين يديك",
        "ku": "کارمەندی گەیاندنەکەت نزیکە زۆر نزیکە! کەمێکی تر داواکارییەکە دەگاتە دەستت"
      },
      {
        "scenario": "Rider Picked Up Order",
        "en": "Your order’s on the way! We’ll let you know when your rider is nearby 🛵",
        "ar": "طلبك في طريقه إليك! سننبهك عندما يقترب السائق من الموقع 🛵",
        "ku": "داواکارییەکەت لە ڕێگەیە! ئاگادارت دەکەینەوە هەرکات نزیک بۆوە 🛵"
      }
    ],
    "sms": [
      {
        "scenario": "Order Dispatched",
        "en": "Get ready! Your order from {REST_NAME} is out for delivery.",
        "ar": "استعد! طلبك من {REST_NAME} في الطريق إليك.",
        "ku": "ئامادەبە! داواکارییەکەت لە {REST_NAME} بەڕێوەیە."
      },
      {
        "scenario": "Order Delayed",
        "en": "Unfortunately your order from {REST_NAME} is delayed. The new expected delivery time is {EDT}. Sorry for the inconvenience.",
        "ar": "نأسف، طلبك من {REST_NAME} سوف يتأخر لعدة دقائق، الوقت المتوقع للوصول هو {EDT}",
        "ku": "ببورە! داواکارییەکەت لە {REST_NAME} دوادەکەوێت. کاتی پێشبینیکراوی نوێ بریتییە لە {EDT}.",
        "delay": true
      },
      {
        "scenario": "Near Customer",
        "en": "Your rider is almost there. Give them a moment to drop off your order.",
        "ar": "مندوب التوصيل على وشك الوصول! لحظات وسيكون طلبك بين يديك.",
        "ku": "کارمەندی گەیاندن نزیکە لێتەوە. کەمێکی تر دەگاتە لات."
      },
      {
        "scenario": "Late Order Check (Agent-sent)",
        "en": "Your order seems to be running late. Please hold on let me check with [RestaurantName].",
        "ar": "يبدو أن طلبك قد تأخر. يرجى الانتظار قليلاً للتأكد من حالة الطلب مع مطعم [RestaurantName].",
        "delay": true
      },
      {
        "scenario": "Bad Weather Delay",
        "en": "Dear [Customer Name], Your order might be slightly delayed due to bad weather conditions",
        "ar": null,
        "delay": true
      },
      {
        "scenario": "Rider Has Card Reader",
        "en": "Want to pay with your card instead of cash? This rider is equipped to take payment with your bank card. Just tap and pay!",
        "ar": "هل تفكّر في الدفع بالبطاقة بدلًا من الدفع نقدًا؟ بسيطة، اطلب من سائق التوصيل، فلديه ماكينة الدفع الإلكتروني. ولا أسهل!"
      },
      {
        "scenario": "Summer Heat Notice",
        "en": "Summer is here! Due to the heat, riders are delivering orders by car so there might be some delays. Thanks for helping our riders keep cool",
        "ar": null,
        "delay": true
      }
    ],
    "email": []
  },
  "delivered": {
    "inapp": {
      "main": [
        {
          "scenario": "Delivered",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Enjoy your order!",
            "ar": "استمتع بطلبك!",
            "ku": "چێژ لە داواکارییەکەت ببینە!"
          },
          "desc": {
            "en": "Your order is right on time 🎉 Unwind and enjoy it!",
            "ar": "طلبك وصل في الوقت المحدد 🎉 استرخي واستمتع بطلبك!",
            "ku": "داواکارییەکەت لە کاتی خۆیدا گەیشت 🎉 چێژی لێ ببینە!"
          }
        },
        {
          "scenario": "Items Out of Stock",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Some items are out of stock",
            "ar": "بعض المنتجات غير متوفرة",
            "ku": "بەشێک لە بابەتەکان بەردەست نین"
          },
          "desc": {
            "en": "Choose replacement",
            "ar": "اختر منتجًا بديلاً",
            "ku": "جێگرەوە هەڵبژێرە"
          }
        },
        {
          "scenario": "Pick Up Ready",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Pick up by",
            "ar": "استلم في",
            "ku": "هەڵگیرا لە"
          },
          "desc": {
            "en": "It's time to go to {VENDOR_NAME} to collect your order",
            "ar": "توجّه إلى {VENDOR_NAME} لاستلام طلبك",
            "ku": "کاتییەتی بچیت بۆ {VENDOR_NAME} بۆ هەڵگرتنی داواکارییەکەت"
          }
        },
        {
          "scenario": "Drone Pickup Ready",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Pick up by",
            "ar": "استلم في",
            "ku": "هەڵگیرا لە"
          },
          "desc": {
            "en": "It's time to go to {VENDOR_NAME} to collect your order. Use code {PICKUP_CODE} at the delivery point",
            "ar": "توجّه إلى {VENDOR_NAME} لاستلام طلبك. استخدم الرمز {PICKUP_CODE} في نقطة التسليم"
          }
        },
        {
          "scenario": "Order Picked Up",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "Order picked up",
          "ar": "تم استلام الطلب",
          "ku": "داواکاری هەڵگیرا"
        },
        {
          "scenario": "Pick Up Ready",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "Ready for pickup",
          "ar": "طلبك جاهز للاستلام",
          "ku": "ئامادەیە بۆ هەڵگرتن"
        },
        {
          "scenario": "Order Cancelled",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "Order cancelled",
          "ar": "تم إلغاء الطلب",
          "ku": "داواکاری هەڵوەشێنرایەوە"
        },
        {
          "scenario": "Delivered (Temp Order)",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "title": {
            "en": "Order delivered",
            "ar": "تم توصيل الطلب",
            "ku": "داواکاری گەیاندرا"
          },
          "desc": {
            "en": "Your order is right on time 🎉 Unwind and enjoy it!",
            "ar": "طلبك وصل في الوقت المحدد 🎉 استرخي واستمتع بطلبك!",
            "ku": "داواکارییەکەت لە کاتی خۆیدا گەیشت 🎉 چێژی لێ ببینە!"
          }
        },
        {
          "scenario": "Delivered Title",
          "surfaces": [
            "homescreen",
            "otp"
          ],
          "en": "Order delivered",
          "ar": "تم توصيل الطلب",
          "ku": "داواکاری گەیاندرا"
        }
      ],
      "compensation": [
        {
          "scenario": "Single Voucher — Banner Title",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Sorry for the delay",
          "ar": "نعتذر عن هذا التأخير.",
          "ku": "زۆر داوای لێبوردن دەکەین بۆ دواکەوتنەکە"
        },
        {
          "scenario": "Single Voucher — Banner Text",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Let us make it up to you with a {AMOUNT} voucher.",
          "ar": "إليك قسيمة بقيمة {AMOUNT} كهدية بسيطة تعويضًا لك.",
          "ku": "دەمانەوێت قەرەبووت بکەینەوە بە کۆبۆنێکی {AMOUNT}"
        },
        {
          "scenario": "Single Voucher — Banner Action",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Claim voucher",
          "ar": "استلم القسيمة",
          "ku": "بەکارهێنانی کۆبۆن"
        },
        {
          "scenario": "Single Voucher — Sheet Title",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "We've added a {AMOUNT} voucher to your account",
          "ar": "أضفنا قسيمة بقيمة {AMOUNT} إلى حسابك.",
          "ku": "کۆبۆنێکی {AMOUNT}مان بۆ جزدانەکەت زیاد کرد"
        },
        {
          "scenario": "Single Voucher — Sheet Text",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Use it on any future order within the next 14 days. To see all your vouchers, go to your account.",
          "ar": "يمكنك استخدامها مع أي طلب قادم.",
          "ku": "بەردەستە بۆ بەکارهێنانی لە هەر داواکارییەکی داهاتووتدا"
        },
        {
          "scenario": "Multiple Vouchers — Banner Title",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Here's {AMOUNT} just for you",
          "ar": "{AMOUNT} خصيصًا لك"
        },
        {
          "scenario": "Multiple Vouchers — Banner Text",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "It’s our way of saying sorry for the delay with your order",
          "ar": "إنها طريقتنا للإعتذار عن التأخير في طلبك"
        },
        {
          "scenario": "Multiple Vouchers — Banner Action",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Claim vouchers",
          "ar": "احصل على القسائم",
          "ku": "بەکارهێنانی کۆبۆن"
        },
        {
          "scenario": "Multiple Vouchers — Sheet Title",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "We’ve added three {AMOUNT} vouchers to your account",
          "ar": "قمنا بإضافة ثلاث قسائم بقيمة {AMOUNT} لحسابك"
        },
        {
          "scenario": "Multiple Vouchers — Sheet Text",
          "delay": true,
          "surfaces": [
            "otp"
          ],
          "en": "Use them on any order within the next 14 days. Find your vouchers at any time by tapping ‘Account’",
          "ar": "قم باستخدامها مع أي طلب خلال 14 يوم. يمكنك إيجاد قسائمك في أي وقت في صفحة \"حسابك\""
        }
      ]
    },
    "push": [],
    "sms": [
      {
        "scenario": "Cancelled — Generic",
        "en": "Unfortunately your order from {REST_NAME} got cancelled. You'll be refunded if you've paid online.",
        "ar": "نأسف، لم نتمكن من تلبية طلبك من {REST_NAME}. سيتم استرداد المدفوعات بنفس طريقة الدفع.",
        "ku": "ببورە داواکارییەکەت لە {REST_NAME} کانسڵ کرا. پارەی دراوت بۆ دەگەڕێتەوە گەر بە ئۆنڵاین پارەت دابێت."
      },
      {
        "scenario": "Cancelled — Customer Unreachable",
        "en": "Hi from Talabat. Your order [Order ID] is cancelled because you were not able to answer our calls.",
        "ar": "مرحبا, تم إلغاء طلبك [Order ID] لأننا لم نستطيع التواصل معك."
      },
      {
        "scenario": "Cancelled — Duplicate Order",
        "en": "Hi from Talabat. Your order [Order ID] was cancelled as it was a duplicate order.",
        "ar": "تم إلغاء الطلب [Order ID] بسبب وجود طلب مطابق. بإمكانك وضع طلب آخر."
      },
      {
        "scenario": "Cancelled — Technical Issue",
        "en": "Hi from Talabat. Unfortunately your order [Order ID] was cancelled due to a technical issue.",
        "ar": "نعتذر. تم إلغاء الطلب [Order ID] بسبب مشكلة تقنية. بإمكانك وضع طلب آخر."
      },
      {
        "scenario": "Cancelled — Bad Weather",
        "en": "Hi from Talabat. Unfortunately your order [Order ID] was cancelled due to environmental circumstances.",
        "ar": "مرحبا. للأسف تم إلغاء طلبك [Order ID] بسبب أحوال بيئية."
      }
    ],
    "email": []
  }
};

// ── Seasonal / Contextual Data (cross-stage, manually maintained) ──
const SEASONAL_DATA = {
  friday_prayer: {
    label: "Friday Prayers",
    messages: [
      { scenario: "Friday Prayers — OTP", en: "It's Friday prayer time so deliveries might take a bit longer, but no worries, we're on it!", ar: "قد يتأخر طلبك قليلاً بسبب صلاة الجمعة، لكن لا تقلق نحن نعمل عليه!", delay: true, surfaces: ["otp"] },
      { scenario: "Friday Prayers — Homescreen", en: "It's a little busy during Friday prayer", ar: "قد يكون هناك بعض التأخير خلال وقت صلاة الجمعة", delay: true, surfaces: ["homescreen"] },
      { scenario: "Friday Prayers — SMS", en: "Thanks for ordering from Talabat.com. Your order is sent to Restaurant & might be delayed due to prayer time.", ar: "شكرا لاختيارك طلبات. من الممكن أن يكون هناك تأخير طفيف في التوصيل بسبب وقت الصلاة.", delay: true },
    ],
  },
  iftar_rush: {
    label: "Ramadan / Peak Iftar",
    messages: [
      { scenario: "Iftar Rush — OTP", en: "It's peak time for Iftar orders! Deliveries might take a bit longer, but we've got this \u{1F4AA}", ar: "إنه وقت الذروة لطلبات الإفطار! قد يكون هناك بعض التأخير في توصيل الطلبات. لكننا نعمل على طلبك \u{1F4AA}", delay: true, surfaces: ["otp"] },
      { scenario: "Iftar Rush — Homescreen", en: "Iftar time's a bit busy, but we've got this!", ar: "إنه وقت الذروة لطلبات الإفطار، لكننا نتابع طلبك!", delay: true, surfaces: ["homescreen"] },
    ],
  },
  new_years: {
    label: "New Year's Eve",
    messages: [
      { scenario: "New Year's Rush — OTP", en: "New Year's countdown is on! Orders might take a little longer due to the rush, but we're on it \u{1F4AA}", ar: "العام الجديد على الأبواب! قد يكون هناك بعض التأخير لزيادة الطلبات، ولكن لا تقلق نحن نعمل على طلبك \u{1F4AA}", delay: true, surfaces: ["otp"] },
    ],
  },
  weather_gps: {
    label: "Weather & GPS Issues",
    messages: [
      { scenario: "Bad Weather Delay — SMS", en: "Dear [Customer Name], Your order might be slightly delayed due to bad weather conditions", ar: null, delay: true },
      { scenario: "Summer Heat Notice — SMS", en: "Summer is here! Due to the heat, riders are delivering orders by car so there might be some delays. Thanks for helping our riders keep cool", ar: null, delay: true },
      { scenario: "Bad Weather Cancellation — SMS", en: "Hi from Talabat. Unfortunately your order [Order ID] was cancelled due to environmental circumstances.", ar: "مرحبا. للأسف تم إلغاء طلبك [Order ID] بسبب أحوال بيئية." },
    ],
  },
};

// ── Surface labels for sections that keep headers ──
const SURFACE_LABELS = {
  timeline: "Order Timeline Bottom Sheet",
  indicators: "Status Indicators & Badges",
  tgo: "TGO In-App Notifications",
  voucher: "On-Time Guarantee (OTG)",
  compensation: "Delay Compensation",
};

// Surfaces that render as headed sections (not merged into main)
const HEADED_SURFACES = ["timeline", "indicators", "tgo", "voucher", "compensation"];

// ── Constants ──
const LANG_ORDER = ["en", "ar", "ku"];
const LANG_LABELS = { en: "EN", ar: "AR", ku: "KU" };
const RTL_LANGS = new Set(["ar", "ku"]);

let activeStage = null;
let activeChannel = "inapp";

// ── Init ──
function init() {
  renderTimeline();
  bindChannelTabs();
  selectStage("order_placed", 0);
}

// ── Timeline ──
function renderTimeline() {
  const container = document.getElementById("timelineStages");
  STAGES.forEach((stage, i) => {
    const node = document.createElement("div");
    node.className = "stage-node";
    node.dataset.index = i;
    node.dataset.id = stage.id;
    node.innerHTML = `
      <div class="stage-dot"></div>
      <div class="stage-label">${stage.label}</div>
    `;
    node.addEventListener("click", () => selectStage(stage.id, i));
    container.appendChild(node);
  });
}

function selectStage(stageId, index) {
  document.querySelectorAll(".stage-node").forEach((n, i) => {
    n.classList.remove("active");
    n.classList.toggle("completed", i < index);
  });
  document.querySelectorAll(".stage-node")[index].classList.add("active");
  const pct = (index / (STAGES.length - 1)) * 100;
  document.getElementById("timelineProgress").style.width = pct + "%";
  activeStage = stageId;
  renderContent();
}

// ── Channel Tabs ──
function bindChannelTabs() {
  document.querySelectorAll(".channel-tab").forEach((tab) => {
    tab.addEventListener("click", () => {
      document.querySelectorAll(".channel-tab").forEach((t) => t.classList.remove("active"));
      tab.classList.add("active");
      activeChannel = tab.dataset.channel;
      renderContent();
    });
  });
}

// ── Render ──
function renderContent() {
  const area = document.getElementById("contentArea");
  if (activeChannel === "seasonal") {
    area.innerHTML = renderSeasonal();
    return;
  }
  if (!activeStage) {
    area.innerHTML = `<div class="empty-state"><p>Select a stage above to see communications</p></div>`;
    return;
  }
  const stageData = DATA[activeStage];
  if (!stageData) {
    area.innerHTML = `<div class="no-messages">No data for this stage</div>`;
    return;
  }
  if (activeChannel === "inapp") {
    area.innerHTML = renderInApp(stageData.inapp);
  } else {
    const channelData = stageData[activeChannel];
    const label = activeChannel === "push" ? "Push Notifications" : activeChannel === "sms" ? "SMS" : "Email";
    area.innerHTML = renderCardList(channelData, label);
  }
}

function renderSeasonal() {
  let html = "";
  Object.values(SEASONAL_DATA).forEach((category) => {
    html += `<div class="surface-section">`;
    html += `<div class="surface-header"><span class="surface-label">${category.label}</span></div>`;
    category.messages.forEach((msg) => { html += renderMsgCard(msg, !!msg.surfaces); });
    html += `</div>`;
  });
  return html || `<div class="no-messages">No seasonal communications</div>`;
}

function renderInApp(inappData) {
  if (!inappData) return `<div class="no-messages">No in-app communications at this stage</div>`;
  let html = "";

  // Main messages (no header — just cards with surface chips)
  if (inappData.main && inappData.main.length > 0) {
    html += `<div class="surface-section">`;
    inappData.main.forEach((msg) => { html += renderMsgCard(msg, true); });
    html += `</div>`;
  }

  // Headed sections
  HEADED_SURFACES.forEach((surface) => {
    const messages = inappData[surface];
    if (!messages || messages.length === 0) return;
    const label = SURFACE_LABELS[surface] || surface;
    html += `<div class="surface-section">`;
    html += `<div class="surface-header"><span class="surface-label">${label}</span></div>`;
    messages.forEach((msg) => { html += renderMsgCard(msg, !!msg.surfaces); });
    html += `</div>`;
  });

  return html || `<div class="no-messages">No in-app communications at this stage</div>`;
}

function renderCardList(messages, label) {
  if (!messages || messages.length === 0) {
    return `<div class="no-messages">No ${label.toLowerCase()} communications at this stage</div>`;
  }
  let html = `<div class="surface-section">`;
  html += `<div class="surface-header"><span class="surface-label">${label}</span></div>`;
  messages.forEach((msg) => { html += renderMsgCard(msg, false); });
  html += `</div>`;
  return html;
}

function renderMsgCard(msg, showSurfaces) {
  const id = "card-" + Math.random().toString(36).slice(2, 8);
  const hasTitleDesc = msg.title;
  const langs = hasTitleDesc
    ? LANG_ORDER.filter((l) => msg.title[l])
    : LANG_ORDER.filter((l) => msg[l]);

  // Build chips
  let chips = "";
  if (msg.delay) chips += '<span class="delay-tag">DELAY</span>';
  if (showSurfaces && msg.surfaces) {
    msg.surfaces.forEach((s) => {
      const label = s === "homescreen" ? "Homescreen" : "OTP";
      chips += `<span class="surface-chip ${s}">${label}</span>`;
    });
  }

  // Build body
  let inner = "";
  if (hasTitleDesc) {
    // Title + Description combined format
    langs.forEach((lang) => {
      const dir = RTL_LANGS.has(lang) ? 'dir="rtl"' : "";
      const titleText = msg.title[lang] || "";
      const descText = msg.desc && msg.desc[lang] ? msg.desc[lang] : "";
      inner += `<div class="lang-row lang-row-combined" ${dir}>`;
      inner += `<span class="lang-label ${lang}">${LANG_LABELS[lang]}</span>`;
      inner += `<div class="combined-text">`;
      inner += `<div class="combined-title">${titleText}</div>`;
      if (descText) inner += `<div class="combined-desc">${descText}</div>`;
      inner += `</div></div>`;
    });
  } else {
    // Simple flat format (substatus, push, sms, etc.)
    langs.forEach((lang) => {
      const dir = RTL_LANGS.has(lang) ? 'dir="rtl"' : "";
      inner += `<div class="lang-row" ${dir}><span class="lang-label ${lang}">${LANG_LABELS[lang]}</span> ${msg[lang]}</div>`;
    });
  }

  return `
    <div class="msg-card" id="${id}">
      <div class="msg-card-header" onclick="document.getElementById('${id}').classList.toggle('open')">
        <div class="msg-card-header-left">
          <span class="msg-card-scenario">${msg.scenario}</span>
          <div class="msg-card-chips">${chips}</div>
        </div>
        <span class="msg-card-chevron">\u25BC</span>
      </div>
      <div class="msg-card-body">
        <div class="msg-card-inner">${inner}</div>
      </div>
    </div>
  `;
}

init();
